### ISSUE TITLE
It looks like ns.uimaps is not defined anywhere

### ISSUE THREAD

**Issue by rowaasr13** [Vladinator/wow-addon-candybuckets#13]
Am I missing anything or `ns.uimaps` is not defined anywhere? Therefore `GetChildrenNS` and calls that use it seems to be useless as well. Quick instrumentation at `GetChildrenNS` shows that it never ever returned anything but `nil` and thus can be removed.

It's only called 19 times, so it isn't a performance problem, yet it distracts from reviewing rest of code.

**Comment by Vladinator** [comment]
I believe I experimented with some additional map overrides that I had in a custom uimaps file but I didn't release it, though the code referencing it remains I see. It simply does nothing when the GetChildrenNS is ran. I guess I should purge it out unless I get around and actually push out the uimaps file, but I doubt it at this point... 😅
