### ISSUE TITLE
Dragon Isles midsummer flames

### ISSUE THREAD

**Issue by p3lim** [Vladinator/wow-addon-candybuckets#27]
![image](https://github.com/Vladinator/wow-addon-candybuckets/assets/26496/0c0c18d2-c6a6-419f-adcc-ecd5be7b139e)
![image](https://github.com/Vladinator/wow-addon-candybuckets/assets/26496/5206c392-272a-4f67-b28f-a779a71a443f)
![image](https://github.com/Vladinator/wow-addon-candybuckets/assets/26496/b0f432ab-c2e7-42a7-98f6-4b4c439ad684)
![image](https://github.com/Vladinator/wow-addon-candybuckets/assets/26496/3fd5ab98-d160-4825-a785-9041f940ea05)
![image](https://github.com/Vladinator/wow-addon-candybuckets/assets/26496/3c532b62-0d6a-48e0-939a-e160b0a3cfb3)

Missing Zaralek (questID 75650), it's roughly 55.65, 55.43 on mapID 2133.

**Comment by Meilinn** [comment]
Same
![Screenshot_138](https://github.com/Vladinator/wow-addon-candybuckets/assets/1574497/a8ccf6c2-97d5-4189-ae85-b70b82547662)

**Comment by Vladinator** [comment]
Thanks! I pushed an update with these new bonfires in the latest release.
